<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-G0D562V" name="com.resurrectionSeleniumARF.TestNgTimeoutAttrib" tests="1" failures="0" timestamp="04 Feb 2020 10:14:21 GMT" time="1.122" errors="1">
  <testcase name="bookTicket" time="1.122" classname="com.resurrectionSeleniumARF.TestNgTimeoutAttrib">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.resurrectionSeleniumARF.TestNgTimeoutAttrib.bookTicket() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.resurrectionSeleniumARF.TestNgTimeoutAttrib.bookTicket() didn't finish within the time-out 1000
at java.lang.Throwable.toString(Unknown Source)
at java.lang.Throwable.<init>(Unknown Source)
at java.lang.Exception.<init>(Unknown Source)
at java.lang.RuntimeException.<init>(Unknown Source)
at org.testng.internal.InvokeMethodRunnable$TestNGRuntimeException.<init>(InvokeMethodRunnable.java:78)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:61)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- bookTicket -->
</testsuite> <!-- com.resurrectionSeleniumARF.TestNgTimeoutAttrib -->
